//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acme.SmartTrackerTaskWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericResult", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    [System.SerializableAttribute()]
    public partial class GenericResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskInfoResult", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    [System.SerializableAttribute()]
    public partial class TaskInfoResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private Acme.SmartTrackerTaskWebService.TaskInfo TaskField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public Acme.SmartTrackerTaskWebService.TaskInfo Task {
            get {
                return this.TaskField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskField, value) != true)) {
                    this.TaskField = value;
                    this.RaisePropertyChanged("Task");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskInfo", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    [System.SerializableAttribute()]
    public partial class TaskInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TaskIDField;
        
        private int TaskPriorityIDField;
        
        private int TaskStatusIDField;
        
        private System.Nullable<int> UserIDField;
        
        private System.Nullable<int> TicketIDField;
        
        private System.Nullable<int> ChatIDField;
        
        private System.Nullable<int> ReminderMinutesField;
        
        private System.Nullable<int> CallLogIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.Nullable<System.DateTime> DateStartField;
        
        private System.Nullable<System.DateTime> DateDueField;
        
        private System.Nullable<int> OriginalEstimateField;
        
        private System.Nullable<int> RemainingEstimateField;
        
        private System.Nullable<int> OriginalEstimateTypeField;
        
        private System.Nullable<int> RemainingEstimateTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((this.TaskIDField.Equals(value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TaskPriorityID {
            get {
                return this.TaskPriorityIDField;
            }
            set {
                if ((this.TaskPriorityIDField.Equals(value) != true)) {
                    this.TaskPriorityIDField = value;
                    this.RaisePropertyChanged("TaskPriorityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TaskStatusID {
            get {
                return this.TaskStatusIDField;
            }
            set {
                if ((this.TaskStatusIDField.Equals(value) != true)) {
                    this.TaskStatusIDField = value;
                    this.RaisePropertyChanged("TaskStatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> TicketID {
            get {
                return this.TicketIDField;
            }
            set {
                if ((this.TicketIDField.Equals(value) != true)) {
                    this.TicketIDField = value;
                    this.RaisePropertyChanged("TicketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> ChatID {
            get {
                return this.ChatIDField;
            }
            set {
                if ((this.ChatIDField.Equals(value) != true)) {
                    this.ChatIDField = value;
                    this.RaisePropertyChanged("ChatID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> ReminderMinutes {
            get {
                return this.ReminderMinutesField;
            }
            set {
                if ((this.ReminderMinutesField.Equals(value) != true)) {
                    this.ReminderMinutesField = value;
                    this.RaisePropertyChanged("ReminderMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> CallLogID {
            get {
                return this.CallLogIDField;
            }
            set {
                if ((this.CallLogIDField.Equals(value) != true)) {
                    this.CallLogIDField = value;
                    this.RaisePropertyChanged("CallLogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<System.DateTime> DateStart {
            get {
                return this.DateStartField;
            }
            set {
                if ((this.DateStartField.Equals(value) != true)) {
                    this.DateStartField = value;
                    this.RaisePropertyChanged("DateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<System.DateTime> DateDue {
            get {
                return this.DateDueField;
            }
            set {
                if ((this.DateDueField.Equals(value) != true)) {
                    this.DateDueField = value;
                    this.RaisePropertyChanged("DateDue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<int> OriginalEstimate {
            get {
                return this.OriginalEstimateField;
            }
            set {
                if ((this.OriginalEstimateField.Equals(value) != true)) {
                    this.OriginalEstimateField = value;
                    this.RaisePropertyChanged("OriginalEstimate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<int> RemainingEstimate {
            get {
                return this.RemainingEstimateField;
            }
            set {
                if ((this.RemainingEstimateField.Equals(value) != true)) {
                    this.RemainingEstimateField = value;
                    this.RaisePropertyChanged("RemainingEstimate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<int> OriginalEstimateType {
            get {
                return this.OriginalEstimateTypeField;
            }
            set {
                if ((this.OriginalEstimateTypeField.Equals(value) != true)) {
                    this.OriginalEstimateTypeField = value;
                    this.RaisePropertyChanged("OriginalEstimateType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<int> RemainingEstimateType {
            get {
                return this.RemainingEstimateTypeField;
            }
            set {
                if ((this.RemainingEstimateTypeField.Equals(value) != true)) {
                    this.RemainingEstimateTypeField = value;
                    this.RaisePropertyChanged("RemainingEstimateType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskInfoResultArray", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    [System.SerializableAttribute()]
    public partial class TaskInfoResultArray : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Acme.SmartTrackerTaskWebService.TaskInfo[] TasksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Acme.SmartTrackerTaskWebService.TaskInfo[] Tasks {
            get {
                return this.TasksField;
            }
            set {
                if ((object.ReferenceEquals(this.TasksField, value) != true)) {
                    this.TasksField = value;
                    this.RaisePropertyChanged("Tasks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", ConfigurationName="SmartTrackerTaskWebService.svcTasksSoap")]
    public interface svcTasksSoap {
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/CreateTask", ReplyAction="*")]
        Acme.SmartTrackerTaskWebService.CreateTaskResponse CreateTask(Acme.SmartTrackerTaskWebService.CreateTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/CreateTask", ReplyAction="*")]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.CreateTaskResponse> CreateTaskAsync(Acme.SmartTrackerTaskWebService.CreateTaskRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/UpdateTask", ReplyAction="*")]
        Acme.SmartTrackerTaskWebService.UpdateTaskResponse UpdateTask(Acme.SmartTrackerTaskWebService.UpdateTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/UpdateTask", ReplyAction="*")]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.UpdateTaskResponse> UpdateTaskAsync(Acme.SmartTrackerTaskWebService.UpdateTaskRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/DeleteTask", ReplyAction="*")]
        Acme.SmartTrackerTaskWebService.DeleteTaskResponse DeleteTask(Acme.SmartTrackerTaskWebService.DeleteTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/DeleteTask", ReplyAction="*")]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.DeleteTaskResponse> DeleteTaskAsync(Acme.SmartTrackerTaskWebService.DeleteTaskRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/GetTaskByID", ReplyAction="*")]
        Acme.SmartTrackerTaskWebService.GetTaskByIDResponse GetTaskByID(Acme.SmartTrackerTaskWebService.GetTaskByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/GetTaskByID", ReplyAction="*")]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTaskByIDResponse> GetTaskByIDAsync(Acme.SmartTrackerTaskWebService.GetTaskByIDRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/GetTasksByUser", ReplyAction="*")]
        Acme.SmartTrackerTaskWebService.GetTasksByUserResponse GetTasksByUser(Acme.SmartTrackerTaskWebService.GetTasksByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/GetTasksByUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByUserResponse> GetTasksByUserAsync(Acme.SmartTrackerTaskWebService.GetTasksByUserRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/GetTasksByChatID" +
            "", ReplyAction="*")]
        Acme.SmartTrackerTaskWebService.GetTasksByChatIDResponse GetTasksByChatID(Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/GetTasksByChatID" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByChatIDResponse> GetTasksByChatIDAsync(Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/GetTasksByTicket" +
            "ID", ReplyAction="*")]
        Acme.SmartTrackerTaskWebService.GetTasksByTicketIDResponse GetTasksByTicketID(Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/GetTasksByTicket" +
            "ID", ReplyAction="*")]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByTicketIDResponse> GetTasksByTicketIDAsync(Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/GetTasksByCallLo" +
            "gID", ReplyAction="*")]
        Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDResponse GetTasksByCallLogID(Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx/GetTasksByCallLo" +
            "gID", ReplyAction="*")]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDResponse> GetTasksByCallLogIDAsync(Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTask", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.CreateTaskRequestBody Body;
        
        public CreateTaskRequest() {
        }
        
        public CreateTaskRequest(Acme.SmartTrackerTaskWebService.CreateTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class CreateTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Acme.SmartTrackerTaskWebService.ArrayOfString parameters;
        
        public CreateTaskRequestBody() {
        }
        
        public CreateTaskRequestBody(string authUserName, string authPassword, Acme.SmartTrackerTaskWebService.ArrayOfString parameters) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTaskResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.CreateTaskResponseBody Body;
        
        public CreateTaskResponse() {
        }
        
        public CreateTaskResponse(Acme.SmartTrackerTaskWebService.CreateTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class CreateTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Acme.SmartTrackerTaskWebService.GenericResult CreateTaskResult;
        
        public CreateTaskResponseBody() {
        }
        
        public CreateTaskResponseBody(Acme.SmartTrackerTaskWebService.GenericResult CreateTaskResult) {
            this.CreateTaskResult = CreateTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTask", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.UpdateTaskRequestBody Body;
        
        public UpdateTaskRequest() {
        }
        
        public UpdateTaskRequest(Acme.SmartTrackerTaskWebService.UpdateTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class UpdateTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int taskID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Acme.SmartTrackerTaskWebService.ArrayOfString parameters;
        
        public UpdateTaskRequestBody() {
        }
        
        public UpdateTaskRequestBody(string authUserName, string authPassword, int taskID, Acme.SmartTrackerTaskWebService.ArrayOfString parameters) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.taskID = taskID;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTaskResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.UpdateTaskResponseBody Body;
        
        public UpdateTaskResponse() {
        }
        
        public UpdateTaskResponse(Acme.SmartTrackerTaskWebService.UpdateTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class UpdateTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Acme.SmartTrackerTaskWebService.GenericResult UpdateTaskResult;
        
        public UpdateTaskResponseBody() {
        }
        
        public UpdateTaskResponseBody(Acme.SmartTrackerTaskWebService.GenericResult UpdateTaskResult) {
            this.UpdateTaskResult = UpdateTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTask", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.DeleteTaskRequestBody Body;
        
        public DeleteTaskRequest() {
        }
        
        public DeleteTaskRequest(Acme.SmartTrackerTaskWebService.DeleteTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class DeleteTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int taskID;
        
        public DeleteTaskRequestBody() {
        }
        
        public DeleteTaskRequestBody(string authUserName, string authPassword, int taskID) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.taskID = taskID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTaskResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.DeleteTaskResponseBody Body;
        
        public DeleteTaskResponse() {
        }
        
        public DeleteTaskResponse(Acme.SmartTrackerTaskWebService.DeleteTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class DeleteTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Acme.SmartTrackerTaskWebService.GenericResult DeleteTaskResult;
        
        public DeleteTaskResponseBody() {
        }
        
        public DeleteTaskResponseBody(Acme.SmartTrackerTaskWebService.GenericResult DeleteTaskResult) {
            this.DeleteTaskResult = DeleteTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaskByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaskByID", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.GetTaskByIDRequestBody Body;
        
        public GetTaskByIDRequest() {
        }
        
        public GetTaskByIDRequest(Acme.SmartTrackerTaskWebService.GetTaskByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class GetTaskByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int taskID;
        
        public GetTaskByIDRequestBody() {
        }
        
        public GetTaskByIDRequestBody(string authUserName, string authPassword, int taskID) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.taskID = taskID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaskByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaskByIDResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.GetTaskByIDResponseBody Body;
        
        public GetTaskByIDResponse() {
        }
        
        public GetTaskByIDResponse(Acme.SmartTrackerTaskWebService.GetTaskByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class GetTaskByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Acme.SmartTrackerTaskWebService.TaskInfoResult GetTaskByIDResult;
        
        public GetTaskByIDResponseBody() {
        }
        
        public GetTaskByIDResponseBody(Acme.SmartTrackerTaskWebService.TaskInfoResult GetTaskByIDResult) {
            this.GetTaskByIDResult = GetTaskByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasksByUser", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.GetTasksByUserRequestBody Body;
        
        public GetTasksByUserRequest() {
        }
        
        public GetTasksByUserRequest(Acme.SmartTrackerTaskWebService.GetTasksByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class GetTasksByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int userID;
        
        public GetTasksByUserRequestBody() {
        }
        
        public GetTasksByUserRequestBody(string authUserName, string authPassword, int userID) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasksByUserResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.GetTasksByUserResponseBody Body;
        
        public GetTasksByUserResponse() {
        }
        
        public GetTasksByUserResponse(Acme.SmartTrackerTaskWebService.GetTasksByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class GetTasksByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByUserResult;
        
        public GetTasksByUserResponseBody() {
        }
        
        public GetTasksByUserResponseBody(Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByUserResult) {
            this.GetTasksByUserResult = GetTasksByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksByChatIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasksByChatID", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequestBody Body;
        
        public GetTasksByChatIDRequest() {
        }
        
        public GetTasksByChatIDRequest(Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class GetTasksByChatIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int chatID;
        
        public GetTasksByChatIDRequestBody() {
        }
        
        public GetTasksByChatIDRequestBody(string authUserName, string authPassword, int chatID) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.chatID = chatID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksByChatIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasksByChatIDResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.GetTasksByChatIDResponseBody Body;
        
        public GetTasksByChatIDResponse() {
        }
        
        public GetTasksByChatIDResponse(Acme.SmartTrackerTaskWebService.GetTasksByChatIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class GetTasksByChatIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByChatIDResult;
        
        public GetTasksByChatIDResponseBody() {
        }
        
        public GetTasksByChatIDResponseBody(Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByChatIDResult) {
            this.GetTasksByChatIDResult = GetTasksByChatIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksByTicketIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasksByTicketID", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequestBody Body;
        
        public GetTasksByTicketIDRequest() {
        }
        
        public GetTasksByTicketIDRequest(Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class GetTasksByTicketIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ticketID;
        
        public GetTasksByTicketIDRequestBody() {
        }
        
        public GetTasksByTicketIDRequestBody(string authUserName, string authPassword, int ticketID) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.ticketID = ticketID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksByTicketIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasksByTicketIDResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.GetTasksByTicketIDResponseBody Body;
        
        public GetTasksByTicketIDResponse() {
        }
        
        public GetTasksByTicketIDResponse(Acme.SmartTrackerTaskWebService.GetTasksByTicketIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class GetTasksByTicketIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByTicketIDResult;
        
        public GetTasksByTicketIDResponseBody() {
        }
        
        public GetTasksByTicketIDResponseBody(Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByTicketIDResult) {
            this.GetTasksByTicketIDResult = GetTasksByTicketIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksByCallLogIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasksByCallLogID", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequestBody Body;
        
        public GetTasksByCallLogIDRequest() {
        }
        
        public GetTasksByCallLogIDRequest(Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class GetTasksByCallLogIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int callLogID;
        
        public GetTasksByCallLogIDRequestBody() {
        }
        
        public GetTasksByCallLogIDRequestBody(string authUserName, string authPassword, int callLogID) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.callLogID = callLogID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTasksByCallLogIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTasksByCallLogIDResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx", Order=0)]
        public Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDResponseBody Body;
        
        public GetTasksByCallLogIDResponse() {
        }
        
        public GetTasksByCallLogIDResponse(Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcTasks.asmx")]
    public partial class GetTasksByCallLogIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByCallLogIDResult;
        
        public GetTasksByCallLogIDResponseBody() {
        }
        
        public GetTasksByCallLogIDResponseBody(Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByCallLogIDResult) {
            this.GetTasksByCallLogIDResult = GetTasksByCallLogIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface svcTasksSoapChannel : Acme.SmartTrackerTaskWebService.svcTasksSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class svcTasksSoapClient : System.ServiceModel.ClientBase<Acme.SmartTrackerTaskWebService.svcTasksSoap>, Acme.SmartTrackerTaskWebService.svcTasksSoap {
        
        public svcTasksSoapClient() {
        }
        
        public svcTasksSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public svcTasksSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcTasksSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcTasksSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Acme.SmartTrackerTaskWebService.CreateTaskResponse Acme.SmartTrackerTaskWebService.svcTasksSoap.CreateTask(Acme.SmartTrackerTaskWebService.CreateTaskRequest request) {
            return base.Channel.CreateTask(request);
        }
        
        public Acme.SmartTrackerTaskWebService.GenericResult CreateTask(string authUserName, string authPassword, Acme.SmartTrackerTaskWebService.ArrayOfString parameters) {
            Acme.SmartTrackerTaskWebService.CreateTaskRequest inValue = new Acme.SmartTrackerTaskWebService.CreateTaskRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.CreateTaskRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.parameters = parameters;
            Acme.SmartTrackerTaskWebService.CreateTaskResponse retVal = ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).CreateTask(inValue);
            return retVal.Body.CreateTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.CreateTaskResponse> Acme.SmartTrackerTaskWebService.svcTasksSoap.CreateTaskAsync(Acme.SmartTrackerTaskWebService.CreateTaskRequest request) {
            return base.Channel.CreateTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.CreateTaskResponse> CreateTaskAsync(string authUserName, string authPassword, Acme.SmartTrackerTaskWebService.ArrayOfString parameters) {
            Acme.SmartTrackerTaskWebService.CreateTaskRequest inValue = new Acme.SmartTrackerTaskWebService.CreateTaskRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.CreateTaskRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.parameters = parameters;
            return ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).CreateTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Acme.SmartTrackerTaskWebService.UpdateTaskResponse Acme.SmartTrackerTaskWebService.svcTasksSoap.UpdateTask(Acme.SmartTrackerTaskWebService.UpdateTaskRequest request) {
            return base.Channel.UpdateTask(request);
        }
        
        public Acme.SmartTrackerTaskWebService.GenericResult UpdateTask(string authUserName, string authPassword, int taskID, Acme.SmartTrackerTaskWebService.ArrayOfString parameters) {
            Acme.SmartTrackerTaskWebService.UpdateTaskRequest inValue = new Acme.SmartTrackerTaskWebService.UpdateTaskRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.UpdateTaskRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.taskID = taskID;
            inValue.Body.parameters = parameters;
            Acme.SmartTrackerTaskWebService.UpdateTaskResponse retVal = ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).UpdateTask(inValue);
            return retVal.Body.UpdateTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.UpdateTaskResponse> Acme.SmartTrackerTaskWebService.svcTasksSoap.UpdateTaskAsync(Acme.SmartTrackerTaskWebService.UpdateTaskRequest request) {
            return base.Channel.UpdateTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.UpdateTaskResponse> UpdateTaskAsync(string authUserName, string authPassword, int taskID, Acme.SmartTrackerTaskWebService.ArrayOfString parameters) {
            Acme.SmartTrackerTaskWebService.UpdateTaskRequest inValue = new Acme.SmartTrackerTaskWebService.UpdateTaskRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.UpdateTaskRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.taskID = taskID;
            inValue.Body.parameters = parameters;
            return ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).UpdateTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Acme.SmartTrackerTaskWebService.DeleteTaskResponse Acme.SmartTrackerTaskWebService.svcTasksSoap.DeleteTask(Acme.SmartTrackerTaskWebService.DeleteTaskRequest request) {
            return base.Channel.DeleteTask(request);
        }
        
        public Acme.SmartTrackerTaskWebService.GenericResult DeleteTask(string authUserName, string authPassword, int taskID) {
            Acme.SmartTrackerTaskWebService.DeleteTaskRequest inValue = new Acme.SmartTrackerTaskWebService.DeleteTaskRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.DeleteTaskRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.taskID = taskID;
            Acme.SmartTrackerTaskWebService.DeleteTaskResponse retVal = ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).DeleteTask(inValue);
            return retVal.Body.DeleteTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.DeleteTaskResponse> Acme.SmartTrackerTaskWebService.svcTasksSoap.DeleteTaskAsync(Acme.SmartTrackerTaskWebService.DeleteTaskRequest request) {
            return base.Channel.DeleteTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.DeleteTaskResponse> DeleteTaskAsync(string authUserName, string authPassword, int taskID) {
            Acme.SmartTrackerTaskWebService.DeleteTaskRequest inValue = new Acme.SmartTrackerTaskWebService.DeleteTaskRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.DeleteTaskRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.taskID = taskID;
            return ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).DeleteTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Acme.SmartTrackerTaskWebService.GetTaskByIDResponse Acme.SmartTrackerTaskWebService.svcTasksSoap.GetTaskByID(Acme.SmartTrackerTaskWebService.GetTaskByIDRequest request) {
            return base.Channel.GetTaskByID(request);
        }
        
        public Acme.SmartTrackerTaskWebService.TaskInfoResult GetTaskByID(string authUserName, string authPassword, int taskID) {
            Acme.SmartTrackerTaskWebService.GetTaskByIDRequest inValue = new Acme.SmartTrackerTaskWebService.GetTaskByIDRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.GetTaskByIDRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.taskID = taskID;
            Acme.SmartTrackerTaskWebService.GetTaskByIDResponse retVal = ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).GetTaskByID(inValue);
            return retVal.Body.GetTaskByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTaskByIDResponse> Acme.SmartTrackerTaskWebService.svcTasksSoap.GetTaskByIDAsync(Acme.SmartTrackerTaskWebService.GetTaskByIDRequest request) {
            return base.Channel.GetTaskByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTaskByIDResponse> GetTaskByIDAsync(string authUserName, string authPassword, int taskID) {
            Acme.SmartTrackerTaskWebService.GetTaskByIDRequest inValue = new Acme.SmartTrackerTaskWebService.GetTaskByIDRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.GetTaskByIDRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.taskID = taskID;
            return ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).GetTaskByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Acme.SmartTrackerTaskWebService.GetTasksByUserResponse Acme.SmartTrackerTaskWebService.svcTasksSoap.GetTasksByUser(Acme.SmartTrackerTaskWebService.GetTasksByUserRequest request) {
            return base.Channel.GetTasksByUser(request);
        }
        
        public Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByUser(string authUserName, string authPassword, int userID) {
            Acme.SmartTrackerTaskWebService.GetTasksByUserRequest inValue = new Acme.SmartTrackerTaskWebService.GetTasksByUserRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.GetTasksByUserRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.userID = userID;
            Acme.SmartTrackerTaskWebService.GetTasksByUserResponse retVal = ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).GetTasksByUser(inValue);
            return retVal.Body.GetTasksByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByUserResponse> Acme.SmartTrackerTaskWebService.svcTasksSoap.GetTasksByUserAsync(Acme.SmartTrackerTaskWebService.GetTasksByUserRequest request) {
            return base.Channel.GetTasksByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByUserResponse> GetTasksByUserAsync(string authUserName, string authPassword, int userID) {
            Acme.SmartTrackerTaskWebService.GetTasksByUserRequest inValue = new Acme.SmartTrackerTaskWebService.GetTasksByUserRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.GetTasksByUserRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.userID = userID;
            return ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).GetTasksByUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Acme.SmartTrackerTaskWebService.GetTasksByChatIDResponse Acme.SmartTrackerTaskWebService.svcTasksSoap.GetTasksByChatID(Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequest request) {
            return base.Channel.GetTasksByChatID(request);
        }
        
        public Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByChatID(string authUserName, string authPassword, int chatID) {
            Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequest inValue = new Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.chatID = chatID;
            Acme.SmartTrackerTaskWebService.GetTasksByChatIDResponse retVal = ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).GetTasksByChatID(inValue);
            return retVal.Body.GetTasksByChatIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByChatIDResponse> Acme.SmartTrackerTaskWebService.svcTasksSoap.GetTasksByChatIDAsync(Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequest request) {
            return base.Channel.GetTasksByChatIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByChatIDResponse> GetTasksByChatIDAsync(string authUserName, string authPassword, int chatID) {
            Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequest inValue = new Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.GetTasksByChatIDRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.chatID = chatID;
            return ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).GetTasksByChatIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Acme.SmartTrackerTaskWebService.GetTasksByTicketIDResponse Acme.SmartTrackerTaskWebService.svcTasksSoap.GetTasksByTicketID(Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequest request) {
            return base.Channel.GetTasksByTicketID(request);
        }
        
        public Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByTicketID(string authUserName, string authPassword, int ticketID) {
            Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequest inValue = new Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.ticketID = ticketID;
            Acme.SmartTrackerTaskWebService.GetTasksByTicketIDResponse retVal = ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).GetTasksByTicketID(inValue);
            return retVal.Body.GetTasksByTicketIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByTicketIDResponse> Acme.SmartTrackerTaskWebService.svcTasksSoap.GetTasksByTicketIDAsync(Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequest request) {
            return base.Channel.GetTasksByTicketIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByTicketIDResponse> GetTasksByTicketIDAsync(string authUserName, string authPassword, int ticketID) {
            Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequest inValue = new Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.GetTasksByTicketIDRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.ticketID = ticketID;
            return ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).GetTasksByTicketIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDResponse Acme.SmartTrackerTaskWebService.svcTasksSoap.GetTasksByCallLogID(Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequest request) {
            return base.Channel.GetTasksByCallLogID(request);
        }
        
        public Acme.SmartTrackerTaskWebService.TaskInfoResultArray GetTasksByCallLogID(string authUserName, string authPassword, int callLogID) {
            Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequest inValue = new Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.callLogID = callLogID;
            Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDResponse retVal = ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).GetTasksByCallLogID(inValue);
            return retVal.Body.GetTasksByCallLogIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDResponse> Acme.SmartTrackerTaskWebService.svcTasksSoap.GetTasksByCallLogIDAsync(Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequest request) {
            return base.Channel.GetTasksByCallLogIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDResponse> GetTasksByCallLogIDAsync(string authUserName, string authPassword, int callLogID) {
            Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequest inValue = new Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequest();
            inValue.Body = new Acme.SmartTrackerTaskWebService.GetTasksByCallLogIDRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.callLogID = callLogID;
            return ((Acme.SmartTrackerTaskWebService.svcTasksSoap)(this)).GetTasksByCallLogIDAsync(inValue);
        }
    }
}
